import {defineField, defineType} from 'sanity'

export default defineType({
  name: 'pageContent',
  title: 'Page Content',
  type: 'document',
  groups: [
    {name: 'contact', title: 'Contact Page', default: true},
    {name: 'services', title: 'Services Page'},
    {name: 'blog', title: 'Blog'},
    {name: 'navigation', title: 'Navigation'},
    {name: 'footer', title: 'Footer'},
    {name: 'sections', title: 'Section Headings'},
  ],
  fields: [
    defineField({
      name: 'contactHeading',
      title: 'Contact Page Heading',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactIntro',
      title: 'Contact Page Intro',
      type: 'text',
      rows: 3,
      group: 'contact',
    }),
    defineField({
      name: 'hireHeading',
      title: 'Hire Section Heading',
      type: 'string',
      group: 'contact',
      description: 'e.g. "Start a Project"',
    }),
    defineField({
      name: 'hireDescription',
      title: 'Hire Section Description',
      type: 'text',
      rows: 3,
      group: 'contact',
    }),
    defineField({
      name: 'hireBullets',
      title: 'Hire Section Bullet Points',
      type: 'array',
      of: [{type: 'string'}],
      group: 'contact',
      description: 'What to include in project inquiry',
    }),
    defineField({
      name: 'hireButtonText',
      title: 'Hire Button Text',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'responseTime',
      title: 'Response Time Text',
      type: 'string',
      group: 'contact',
      description: 'e.g. "Typically responds within 24 hours"',
    }),
    defineField({
      name: 'helloHeading',
      title: 'Hello Section Heading',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'helloDescription',
      title: 'Hello Section Description',
      type: 'text',
      rows: 3,
      group: 'contact',
    }),
    defineField({
      name: 'helloButtonText',
      title: 'Hello Button Text',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'servicesHeading',
      title: 'Services Page Heading',
      type: 'string',
      group: 'services',
    }),
    defineField({
      name: 'servicesIntro',
      title: 'Services Page Intro',
      type: 'text',
      rows: 3,
      group: 'services',
    }),
    defineField({
      name: 'servicesCta',
      title: 'Services Bottom CTA Heading',
      type: 'string',
      group: 'services',
    }),
    defineField({
      name: 'servicesCtaDescription',
      title: 'Services Bottom CTA Description',
      type: 'text',
      rows: 3,
      group: 'services',
    }),
    defineField({
      name: 'serviceDetailCtaHeading',
      title: 'Service Detail CTA Heading',
      type: 'string',
      group: 'services',
      description: 'CTA heading on service detail pages',
    }),
    defineField({
      name: 'serviceDetailCtaDescription',
      title: 'Service Detail CTA Description',
      type: 'string',
      group: 'services',
      description: 'CTA description on service detail pages',
    }),
    defineField({
      name: 'serviceDetailCtaButtonText',
      title: 'Service Detail CTA Button Text',
      type: 'string',
      group: 'services',
      description: 'CTA button text on service detail pages',
    }),
    defineField({
      name: 'navItems',
      title: 'Navigation Items',
      type: 'array',
      of: [{
        type: 'object',
        name: 'navItem',
        fields: [
          defineField({name: 'label', title: 'Label', type: 'string', validation: (rule) => rule.required()}),
          defineField({name: 'href', title: 'Link', type: 'string', validation: (rule) => rule.required()}),
        ],
        preview: {select: {title: 'label', subtitle: 'href'}},
      }],
      group: 'navigation',
    }),
    defineField({
      name: 'footerTagline',
      title: 'Footer Tagline',
      type: 'string',
      group: 'footer',
      description: 'Short description in the footer',
    }),
    defineField({
      name: 'aboutHeading',
      title: 'About Heading',
      type: 'string',
      group: 'sections',
      description: 'About section title',
    }),
    defineField({
      name: 'experienceHeading',
      title: 'Experience Heading',
      type: 'string',
      group: 'sections',
      description: 'Experience section title',
    }),
    defineField({
      name: 'projectsHeading',
      title: 'Projects Heading',
      type: 'string',
      group: 'sections',
      description: 'Projects section title',
    }),
    defineField({
      name: 'skillsHeading',
      title: 'Skills Heading',
      type: 'string',
      group: 'sections',
      description: 'Skills/Technologies section title',
    }),
    defineField({
      name: 'homelabHeading',
      title: 'Homelab Heading',
      type: 'string',
      group: 'sections',
      description: 'Homelab section title',
    }),
    defineField({
      name: 'homelabSubtitle',
      title: 'Homelab Subtitle',
      type: 'string',
      group: 'sections',
      description: 'Homelab section subtitle',
    }),
    defineField({
      name: 'certificationsHeading',
      title: 'Certifications Heading',
      type: 'string',
      group: 'sections',
      description: 'Certifications section title',
    }),
    defineField({
      name: 'blogPreviewHeading',
      title: 'Blog Preview Heading',
      type: 'string',
      group: 'sections',
      description: 'Blog preview section title on home page',
    }),
    defineField({
      name: 'contactSectionHeading',
      title: 'Contact Section Heading',
      type: 'string',
      group: 'sections',
      description: 'Contact section heading on home page',
    }),
    defineField({
      name: 'contactSectionTagline',
      title: 'Contact Section Tagline',
      type: 'string',
      group: 'sections',
      description: 'Contact section tagline on home page',
    }),
    defineField({
      name: 'floatingCtaText',
      title: 'Floating CTA Text',
      type: 'string',
      group: 'sections',
      description: 'Floating CTA button text, e.g. Available for hire',
    }),
    defineField({
      name: 'blogPageHeading',
      title: 'Blog Page Heading',
      type: 'string',
      group: 'blog',
      description: 'Blog index page heading',
    }),
    defineField({
      name: 'blogPageSubtitle',
      title: 'Blog Page Subtitle',
      type: 'string',
      group: 'blog',
      description: 'Blog index page subtitle',
    }),
  ],
  preview: {
    prepare() {
      return {title: 'Page Content'}
    },
  },
})
