import {defineType, defineField} from 'sanity'

export default defineType({
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  groups: [
    {name: 'general', title: 'General', default: true},
    {name: 'theme', title: 'Theme Colors'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'siteName',
      title: 'Site Name',
      type: 'string',
      group: 'general',
      validation: (rule) => rule.required(),
      initialValue: 'Hrolgar',
    }),
    defineField({
      name: 'siteDescription',
      title: 'Site Description',
      type: 'text',
      rows: 3,
      group: 'general',
      description: 'Used in meta tags and as default page description',
    }),
    defineField({
      name: 'showBlog',
      title: 'Show Blog',
      type: 'boolean',
      group: 'general',
      initialValue: true,
      description: 'Show blog section on homepage and blog link in navigation',
    }),
    defineField({
      name: 'ogImage',
      title: 'Default Social Image',
      type: 'image',
      group: 'seo',
      description: 'Used when sharing on social media (1200x630 recommended)',
    }),
    defineField({
      name: 'primaryColor',
      title: 'Primary Color',
      type: 'string',
      group: 'theme',
      description: 'Hex color. Default: #5eaba8',
      validation: (rule) => rule.regex(/^#[0-9a-fA-F]{6}$/, { name: 'hex color' }),
    }),
    defineField({
      name: 'secondaryColor',
      title: 'Secondary Color',
      type: 'string',
      group: 'theme',
      description: 'Hex color. Default: #7ec8c5',
      validation: (rule) => rule.regex(/^#[0-9a-fA-F]{6}$/, { name: 'hex color' }),
    }),
    defineField({
      name: 'accentColor',
      title: 'Accent Color',
      type: 'string',
      group: 'theme',
      description: 'Hex color. Default: #e07a5f',
      validation: (rule) => rule.regex(/^#[0-9a-fA-F]{6}$/, { name: 'hex color' }),
    }),
    defineField({
      name: 'backgroundColor',
      title: 'Background Color',
      type: 'string',
      group: 'theme',
      description: 'Hex color. Default: #111116',
      validation: (rule) => rule.regex(/^#[0-9a-fA-F]{6}$/, { name: 'hex color' }),
    }),
    defineField({
      name: 'surfaceColor',
      title: 'Surface Color',
      type: 'string',
      group: 'theme',
      description: 'Hex color. Default: #1a1a22',
      validation: (rule) => rule.regex(/^#[0-9a-fA-F]{6}$/, { name: 'hex color' }),
    }),
    defineField({
      name: 'textColor',
      title: 'Text Color',
      type: 'string',
      group: 'theme',
      description: 'Hex color. Default: #e8e4e0',
      validation: (rule) => rule.regex(/^#[0-9a-fA-F]{6}$/, { name: 'hex color' }),
    }),
    defineField({
      name: 'textSecondaryColor',
      title: 'Text Secondary Color',
      type: 'string',
      group: 'theme',
      description: 'Hex color. Default: #9a9590',
      validation: (rule) => rule.regex(/^#[0-9a-fA-F]{6}$/, { name: 'hex color' }),
    }),
  ],
  preview: {
    select: {title: 'siteName'},
    prepare({title}) {
      return {title: title || 'Site Settings'}
    },
  },
})
